version = 1

[merge]
method = "squash"
delete_branch_on_merge = true
optimistic_updates = true
prioritize_ready_to_merge = true

[merge.message]
title = "pull_request_title"
body = "github_default"
strip_html_comments = true

[update]
always = true

[approve]
auto_approve_usernames = ["1gtm", "tamalsaha"]
